# Generated by Django 4.2.1 on 2023-05-24 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webProjectDjango', '0002_vacation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacation',
            old_name='end_date',
            new_name='from_date',
        ),
        migrations.RenameField(
            model_name='vacation',
            old_name='start_date',
            new_name='to_date',
        ),
    ]
