# Generated by Django 4.2.1 on 2023-05-24 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webProjectDjango', '0003_rename_end_date_vacation_from_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacation',
            old_name='employee_id',
            new_name='employee',
        ),
    ]
